### ISSUE TITLE
Installing daiquiri on a local machine

### ISSUE THREAD

**Issue by naronatrhea** [django-daiquiri/daiquiri-docker-compose#2]
Hi,

First of all, thank you for your work on daiquiri. I have a question regarding the usage of the application to retrieve star data from a local machine installation.

For that I have just followed the wiki that you have provided with default values replacing the <DOCKERHOST> by its actual IP on my machine which is 172.17.0.1 before using the **make** command.

I tried a code sample to retrieve star data from the official gaia server using the route http://gea.esac.esa.int/tap-server/tap with an ADQL/SQL query which works fine.

However when trying on the local installation using 172.17.0.1:9494, it seems that it does not go as smoothly. I am not sure what I did wrong in the configuration  or maybe its the route im using which is wrong.

I have attached the response error (html) which hopefully will lead to an obvious problem for you. (sorry i had to rename the file extension to txt to that I could load it here)

[dockerhost_error.txt](https://github.com/django-daiquiri/daiquiri-docker-compose/files/3681317/dockerhost_error.txt)

Thank you in advance for your help.
Regards.

**Comment by galkinAIP** [comment]
Hi, 

sorrry for the long response time! The docker setup is currently in development stage, the recent commits should have fixed most of the issues it previously had.
